apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rido-hello-world-deployment
  labels: 
     app: hello-world

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-world

  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: rido4good/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
